language: java

jdk:
  - openjdk8

branches:  

services:  
    # Enable docker service inside travis
    - docker

before_install:
    - mkdir --parents $HOME/.m2/repository/net/etri/net.etri.pkilib/1.4/
    - cp MMSServer/External\ Jars/pkilib-1.4.jar $HOME/.m2/repository/net/etri/net.etri.pkilib/1.4/net.etri.pkilib-1.4.jar

install:
    # Build the spring boot app and copy the result to the docker folder
    - mvn clean install && cp MMSServer/target/MC_MMS-0.9.3-SNAPSHOT.jar docker/MMSServer/MMSServer.jar && cp MMSServer/target/MC_MMS-0.9.3-SNAPSHOT.jar docker/MNSDummy/MMSServer.jar
    - cp -r MMSServer/target/lib docker/MMSServer/ && cp -r MMSServer/target/lib docker/MNSDummy/
    - cp -r MMSServer/MMS-configuration docker/MMSServer/

before_script:  
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
    - docker build --no-cache -t lovesm135/mmsserver docker/MMSServer
    - docker tag lovesm135/mmsserver lovesm135/mmsserver:0.9.3
    - docker push lovesm135/mmsserver:0.9.3
    - docker build --no-cache -t lovesm135/mnsdummy docker/MNSDummy
    - docker tag lovesm135/mnsdummy lovesm135/mnsdummy:0.9.3
    - docker push lovesm135/mnsdummy:0.9.3
 

branches:
  only:
    - master
    - stable
    - beta-0.9.3
  except:
    - legacy
    - experimental
#--------------------------------------------
#Autho deployment script is now in development stage.
#deploy:
#  # deploy develop to the staging environment
#  - provider: script
#    script: bash scripts/deploy.sh staging
#    on:
#      branch: develop
#  # deploy master to production
#  - provider: script
#    script: bash scripts/deploy.sh production
#    on:
#      branch: master
#--------------------------------------------
